name: Build ubuntu qcow2

on:
  repository_dispatch:
  workflow_dispatch:

env:
  TZ: America/New_York

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    strategy:
      matrix:
        os_release: [
          'ubuntu-24.04.2-live-server-amd64.iso',
          'ubuntu-24.04.1-live-server-amd64.iso',
          'ubuntu-24.04-live-server-amd64.iso',
          'ubuntu-22.04.5-live-server-amd64.iso',
          'ubuntu-22.04.4-live-server-amd64.iso',
          'ubuntu-22.04.3-live-server-amd64.iso',
          'ubuntu-22.04.2-live-server-amd64.iso',
          'ubuntu-22.04.1-live-server-amd64.iso',
          'ubuntu-22.04-live-server-amd64.iso',
          'ubuntu-20.04.5-live-server-amd64.iso',
          'ubuntu-20.04.4-live-server-amd64.iso',
          'ubuntu-20.04.3-live-server-amd64.iso',
          'ubuntu-20.04.2-live-server-amd64.iso',
          'ubuntu-20.04.1-live-server-amd64.iso',
          'ubuntu-20.04-live-server-amd64.iso',
        ]
      max-parallel: 64
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -qq -y qemu-kvm libvirt-daemon-system virtinst cpu-checker rar aria2 &> /dev/null
          sudo systemctl enable --now libvirtd
          sudo mkdir -p /builder/release

      - name: Build rootfs in vm
        id: build_vm
        timeout-minutes: 20
        working-directory: /builder/
        run: |
          set -x
          sudo /bin/cp -a ${{ github.workspace }}/* .
          ls -alh
          cd iso/${{ matrix.os_release }}
          sudo ./build-vm.sh
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compress Rootfs image
        id: compress_output
        working-directory: /builder/kdev.git/iso/${{ matrix.os_release }}
        run: |
          set -x
          sudo chown -R runner.runner /builder
          ls -alh
          mv kdev.log /builder/release/kdev_${{ matrix.os_release }}.log
          zstd -9 rootfs.qcow2 -o /builder/release/kdev_${{ matrix.os_release }}.qcow2.zst
          sha256sum /builder/release/kdev_${{ matrix.os_release }}.qcow2.zst > /builder/release/kdev_${{ matrix.os_release }}.qcow2.zst.sha256
          rar a /builder/release/kdev_${{ matrix.os_release }}.qcow2.rar rootfs.qcow2
          sha256sum /builder/release/kdev_${{ matrix.os_release }}.qcow2.rar > /builder/release/kdev_${{ matrix.os_release }}.qcow2.rar.sha256
          ls -alh /builder/release/
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload image to release
        uses: ncipollo/release-action@main
        timeout-minutes: 10
        with:
          tag: ubuntu-qcow2
          artifacts: /builder/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: | # ubuntu qcow2

            ### kdev release
            - 默认用户名(Default username): kdev
            - 默认密码(Default password): linux

